version: '3.8'

services:
  alpine: &base
    build:
      context: .
      dockerfile: containers/alpine/Dockerfile
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - .:/src
    working_dir: /src
  debian:
    <<: *base
    build:
      context: .
      dockerfile: containers/debian/Dockerfile
  centos7:
    <<: *base
    build:
      context: .
      dockerfile: containers/centos7/Dockerfile
